#############################################################################
# Makefile for building: EnI
# Generated by qmake (2.01a) (Qt 4.7.1) on: Mon Jun 6 21:17:07 2011
# Project:  EnI.pro
# Template: app
# Command: /Users/ZachR/QtSDK/Desktop/Qt/471/gcc/bin/qmake -spec ../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/macx-g++ QMLJSDEBUGGER_PATH=/Users/ZachR/QtSDK/Qt\ Creator.app/Contents/Resources/qml/qmljsdebugger -o Makefile EnI.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/macx-g++ -I. -I../../../QtSDK/Desktop/Qt/471/gcc/lib/QtCore.framework/Versions/4/Headers -I/Users/ZachR/QtSDK/Desktop/Qt/471/gcc/include/QtCore -I../../../QtSDK/Desktop/Qt/471/gcc/include -ICode/Lua/5.1.4_osx/include -I/Library/Frameworks/SDL.framework/Versions/A/Headers -I/Library/Frameworks/SDL_image.framework/Versions/A/Headers -I/Library/Frameworks/SDL_ttf.framework/Versions/A/Headers -I/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I. -F/Users/ZachR/QtSDK/Desktop/Qt/471/gcc/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Users/ZachR/QtSDK/Desktop/Qt/471/gcc/lib -L/Users/ZachR/QtSDK/Desktop/Qt/471/gcc/lib Lua/5.1.4_osx/liblua5.1.dylib -I/Library/Frameworks/SDL.framework/Headers -I/Library/Frameworks/SDL_image.framework/Headers -I/Library/Frameworks/SDL_ttf.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers SDLMain.m -framework SDL -framework SDL_image -framework SDL_ttf -framework Cocoa -framework OpenGL -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/ZachR/QtSDK/Desktop/Qt/471/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Video.cpp \
		TTF.cpp \
		Surfaces.cpp \
		Rendering.cpp \
		main.cpp \
		Lua.cpp \
		Events.cpp 
OBJECTS       = Video.o \
		TTF.o \
		Surfaces.o \
		Rendering.o \
		main.o \
		Lua.o \
		Events.o
DIST          = ../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/common/unix.conf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/common/mac.conf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/common/mac-g++.conf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/qconfig.pri \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/qt_functions.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/qt_config.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/exclusive_builds.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/default_pre.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/mac/default_pre.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/release.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/default_post.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/mac/default_post.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/mac/x86_64.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/mac/objective_c.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/warn_on.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/qt.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/unix/thread.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/moc.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/mac/rez.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/mac/sdk.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/resources.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/uic.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/yacc.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/lex.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/include_source_dir.prf \
		EnI.pro
QMAKE_TARGET  = EnI
DESTDIR       = 
TARGET        = EnI

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: EnI.pro  ../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/macx-g++/qmake.conf ../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/common/unix.conf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/common/mac.conf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/common/mac-g++.conf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/qconfig.pri \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/qt_functions.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/qt_config.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/exclusive_builds.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/default_pre.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/mac/default_pre.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/release.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/default_post.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/mac/default_post.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/mac/x86_64.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/mac/objective_c.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/warn_on.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/qt.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/unix/thread.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/moc.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/mac/rez.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/mac/sdk.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/resources.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/uic.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/yacc.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/lex.prf \
		../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/macx-g++ QMLJSDEBUGGER_PATH=/Users/ZachR/QtSDK/Qt\ Creator.app/Contents/Resources/qml/qmljsdebugger -o Makefile EnI.pro
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/common/unix.conf:
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/common/mac.conf:
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/common/mac-g++.conf:
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/qconfig.pri:
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/modules/qt_webkit_version.pri:
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/qt_functions.prf:
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/qt_config.prf:
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/exclusive_builds.prf:
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/default_pre.prf:
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/mac/default_pre.prf:
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/release.prf:
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/default_post.prf:
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/mac/default_post.prf:
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/mac/x86_64.prf:
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/mac/objective_c.prf:
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/warn_on.prf:
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/qt.prf:
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/unix/thread.prf:
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/moc.prf:
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/mac/rez.prf:
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/mac/sdk.prf:
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/resources.prf:
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/uic.prf:
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/yacc.prf:
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/lex.prf:
../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec ../../../QtSDK/Desktop/Qt/471/gcc/mkspecs/macx-g++ QMLJSDEBUGGER_PATH=/Users/ZachR/QtSDK/Qt\ Creator.app/Contents/Resources/qml/qmljsdebugger -o Makefile EnI.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/EnI1.0.0 || $(MKDIR) .tmp/EnI1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/EnI1.0.0/ && $(COPY_FILE) --parents Video.h TTF.h Surfaces.h SDLMain.h Rendering.h Lua.h Global.h Events.h Config.h .tmp/EnI1.0.0/ && $(COPY_FILE) --parents Video.cpp TTF.cpp Surfaces.cpp Rendering.cpp main.cpp Lua.cpp Events.cpp .tmp/EnI1.0.0/ && (cd `dirname .tmp/EnI1.0.0` && $(TAR) EnI1.0.0.tar EnI1.0.0 && $(COMPRESS) EnI1.0.0.tar) && $(MOVE) `dirname .tmp/EnI1.0.0`/EnI1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/EnI1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

Video.o: Video.cpp Video.h \
		Surfaces.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Video.o Video.cpp

TTF.o: TTF.cpp TTF.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TTF.o TTF.cpp

Surfaces.o: Surfaces.cpp Surfaces.h \
		Rendering.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Surfaces.o Surfaces.cpp

Rendering.o: Rendering.cpp Rendering.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Rendering.o Rendering.cpp

main.o: main.cpp Config.h \
		Lua.h \
		Lua/5.1.4_osx/include/lua.h \
		Lua/5.1.4_osx/include/luaconf.h \
		Lua/5.1.4_osx/include/lualib.h \
		Lua/5.1.4_osx/include/lauxlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Lua.o: Lua.cpp Lua.h \
		Lua/5.1.4_osx/include/lua.h \
		Lua/5.1.4_osx/include/luaconf.h \
		Lua/5.1.4_osx/include/lualib.h \
		Lua/5.1.4_osx/include/lauxlib.h \
		Video.h \
		Events.h \
		Rendering.h \
		Surfaces.h \
		Config.h \
		TTF.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Lua.o Lua.cpp

Events.o: Events.cpp Events.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Events.o Events.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

